name: GitHub CI

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/*'
      - '.github/*TEMPLATE/**'
    branches:
      - '**'
  pull_request:
    paths-ignore:
      - '*.md'
      - '.github/*'
      - '.github/*TEMPLATE/**'
env:
  is_pr: ${{ startsWith(github.ref, 'refs/pull/') }}
  repo_default: 'ergo720/nxbx'

jobs:
  build:
    name: ${{ matrix.platform }} (${{ matrix.arch }}, ${{ matrix.configuration }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        cmake-generator:
          # x64 arch
          - -A x64 # Visual Studio (latest IDE)
          - -G "Unix Makefiles"
          #- -G Xcode
        configuration: [Debug, Release]
        include:
          - cmake-generator: -A x64
            platform: Windows
            os: windows-latest
            arch: x64
            cmake-build-param: -j $env:NUMBER_OF_PROCESSORS
            folder: win
          - cmake-generator: -G "Unix Makefiles"
            platform: Linux
            os: ubuntu-latest
            arch: x64
            cmake-build-param: -j $(nproc --all)
            folder: linux
          #- cmake-generator: -G Xcode
          #  platform: macOS
          #  os: macos-latest
          #  arch: x64
          #  cmake-build-param: -j $(sysctl -n hw.ncpu)
          #  folder: macos
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Generate CMake Files
        # NOTES:
        # -Werror=dev is used to validate CMakeLists.txt for any faults.
        run: cmake -B build -Werror=dev ${{ matrix.cmake-generator }}
      - name: Build
        run: cmake --build build --config ${{ matrix.configuration }} ${{ matrix.cmake-build-param }}
      #- name: CTests
      #  run: ctest --test-dir build --build-config ${{ matrix.configuration }} --verbose
      #- name: Copy Files
      #  if: matrix.configuration == 'Release'
      #  run: cmake --install build --config ${{ matrix.configuration }} --prefix upload/${{ matrix.folder }}_${{ matrix.arch }}
      #- name: Upload Build Artifact
      #  if: matrix.configuration == 'Release'
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: nxbx
      #    # roughly translate to upload/<platform_arch>/<bin | lib | include>/<anything in here and after>
      #    path: upload/*/*/*
      #    if-no-files-found: error
      #- name: Upload Misc Artifact
      #  if: matrix.cmake-generator == '-G "Unix Makefiles"' && matrix.configuration == 'Release'
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: nxbx
      #    path: |
      #      README.md
      #      LICENSE
      #    if-no-files-found: error
